name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build +nightly --verbose --release
    - name: Run tests
      run: cargo test +nighlty --verbose --release
    - name: Code Lines Badge
      uses: Kherrisan/cloc-badge-action@1.0.1
    
